#!/usr/bin/env python3
"""
HTML Report Generator

Generate an interactive HTML report for stale TODOs.
Usage: python generate_html_report.py <directory> --output report.html
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stale TODO Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #e4e4e4;
            min-height: 100vh;
            padding: 2rem;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { 
            font-size: 2.5rem; 
            margin-bottom: 0.5rem;
            background: linear-gradient(90deg, #00d4ff, #7b2cbf);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        .subtitle { color: #888; margin-bottom: 2rem; }
        .stats { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
            gap: 1rem; 
            margin-bottom: 2rem; 
        }
        .stat-card {
            background: rgba(255,255,255,0.05);
            border-radius: 12px;
            padding: 1.5rem;
            border: 1px solid rgba(255,255,255,0.1);
        }
        .stat-card h3 { font-size: 2rem; margin-bottom: 0.5rem; }
        .stat-card p { color: #888; }
        .ancient h3 { color: #ff6b6b; }
        .stale h3 { color: #ffa94d; }
        .aging h3 { color: #ffd43b; }
        .recent h3 { color: #69db7c; }
        .section { margin-bottom: 2rem; }
        .section-title { 
            font-size: 1.25rem; 
            margin-bottom: 1rem; 
            display: flex; 
            align-items: center; 
            gap: 0.5rem; 
        }
        .badge {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.875rem;
            font-weight: 600;
        }
        .badge-ancient { background: rgba(255,107,107,0.2); color: #ff6b6b; }
        .badge-stale { background: rgba(255,169,77,0.2); color: #ffa94d; }
        .badge-aging { background: rgba(255,212,59,0.2); color: #ffd43b; }
        .badge-recent { background: rgba(105,219,124,0.2); color: #69db7c; }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            background: rgba(255,255,255,0.02);
            border-radius: 8px;
            overflow: hidden;
        }
        th, td { 
            padding: 1rem; 
            text-align: left; 
            border-bottom: 1px solid rgba(255,255,255,0.05); 
        }
        th { 
            background: rgba(255,255,255,0.05); 
            font-weight: 600;
            color: #aaa;
        }
        tr:hover { background: rgba(255,255,255,0.03); }
        .file-path { font-family: monospace; color: #00d4ff; }
        .content { color: #ccc; max-width: 400px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
        .age { font-weight: 600; }
        .footer { margin-top: 3rem; text-align: center; color: #666; font-size: 0.875rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔍 Stale TODO Report</h1>
        <p class="subtitle">Generated: {generated_date} | Directory: {directory}</p>
        
        <div class="stats">
            <div class="stat-card ancient">
                <h3>{ancient_count}</h3>
                <p>🔴 Ancient (&gt;1 year)</p>
            </div>
            <div class="stat-card stale">
                <h3>{stale_count}</h3>
                <p>🟠 Stale (6-12 months)</p>
            </div>
            <div class="stat-card aging">
                <h3>{aging_count}</h3>
                <p>🟡 Aging (3-6 months)</p>
            </div>
            <div class="stat-card recent">
                <h3>{recent_count}</h3>
                <p>🟢 Recent (&lt;3 months)</p>
            </div>
        </div>
        
        {sections}
        
        <div class="footer">
            Generated by stale-todo-finder skill
        </div>
    </div>
</body>
</html>'''

SECTION_TEMPLATE = '''
<div class="section">
    <h2 class="section-title">
        <span class="badge badge-{category}">{emoji} {label}</span>
        <span>({count} found)</span>
    </h2>
    <table>
        <thead>
            <tr>
                <th>File</th>
                <th>Line</th>
                <th>Age</th>
                <th>Author</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
</div>
'''

ROW_TEMPLATE = '''<tr>
    <td class="file-path">{file}</td>
    <td>{line}</td>
    <td class="age">{age}d</td>
    <td>{author}</td>
    <td class="content" title="{content}">{content_short}</td>
</tr>'''


def parse_args():
    parser = argparse.ArgumentParser(description='Generate HTML report for stale TODOs')
    parser.add_argument('directory', nargs='?', default='.')
    parser.add_argument('--output', default='stale_todos.html')
    parser.add_argument('--min-age', type=int, default=0)
    return parser.parse_args()


# Simplified TODO finding and git blame (reusing logic from other scripts)
def find_and_analyze(directory, min_age):
    """Find TODOs and analyze their age."""
    # This is a simplified version - in production, import from analyze_staleness.py
    results = []
    patterns = ['TODO', 'FIXME', 'HACK', 'XXX', 'BUG']
    pattern_regex = re.compile(r'\b(' + '|'.join(patterns) + r')\b[:\s]*(.*)$', re.IGNORECASE)
    extensions = {'.py', '.js', '.ts', '.jsx', '.tsx', '.go', '.java'}
    skip_dirs = {'node_modules', 'vendor', 'venv', '.git', 'dist', 'build'}
    
    root = Path(directory).resolve()
    
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip_dirs]
        
        for filename in filenames:
            file_path = Path(dirpath) / filename
            if file_path.suffix.lower() not in extensions:
                continue
            
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    for line_num, line in enumerate(f, 1):
                        match = pattern_regex.search(line)
                        if match:
                            rel_path = file_path.relative_to(root)
                            # Get git blame
                            blame = get_blame(rel_path, line_num, root)
                            if blame and blame['age_days'] >= min_age:
                                results.append({
                                    'file': str(rel_path),
                                    'line': line_num,
                                    'content': match.group(2).strip()[:100],
                                    'author': blame['author'],
                                    'age_days': blame['age_days'],
                                    'category': categorize(blame['age_days'])
                                })
            except Exception:
                pass
    
    results.sort(key=lambda x: -x['age_days'])
    return results


def get_blame(file_path, line_num, repo_root):
    """Get git blame info for a line."""
    try:
        result = subprocess.run(
            ['git', 'blame', '-L', f'{line_num},{line_num}', '--porcelain', str(file_path)],
            cwd=repo_root, capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return None
        
        author = 'Unknown'
        author_time = None
        for line in result.stdout.split('\n'):
            if line.startswith('author '):
                author = line[7:]
            elif line.startswith('author-time '):
                author_time = datetime.fromtimestamp(int(line[12:]))
        
        if author_time:
            return {'author': author, 'age_days': (datetime.now() - author_time).days}
    except Exception:
        pass
    return None


def categorize(age_days):
    if age_days > 365: return 'ancient'
    elif age_days > 180: return 'stale'
    elif age_days > 90: return 'aging'
    return 'recent'


def generate_html(results, directory):
    """Generate HTML report."""
    categories = {'ancient': [], 'stale': [], 'aging': [], 'recent': []}
    for r in results:
        categories[r['category']].append(r)
    
    sections_html = ''
    cat_info = {
        'ancient': ('🔴', 'Ancient (>1 year)'),
        'stale': ('🟠', 'Stale (6-12 months)'),
        'aging': ('🟡', 'Aging (3-6 months)'),
        'recent': ('🟢', 'Recent (<3 months)')
    }
    
    for cat in ['ancient', 'stale', 'aging', 'recent']:
        items = categories[cat]
        if not items:
            continue
        
        rows_html = ''
        for item in items:
            rows_html += ROW_TEMPLATE.format(
                file=item['file'],
                line=item['line'],
                age=item['age_days'],
                author=item['author'],
                content=item['content'].replace('<', '&lt;').replace('>', '&gt;'),
                content_short=item['content'][:50]
            )
        
        emoji, label = cat_info[cat]
        sections_html += SECTION_TEMPLATE.format(
            category=cat,
            emoji=emoji,
            label=label,
            count=len(items),
            rows=rows_html
        )
    
    return HTML_TEMPLATE.format(
        generated_date=datetime.now().strftime('%Y-%m-%d %H:%M'),
        directory=directory,
        ancient_count=len(categories['ancient']),
        stale_count=len(categories['stale']),
        aging_count=len(categories['aging']),
        recent_count=len(categories['recent']),
        sections=sections_html
    )


def main():
    args = parse_args()
    
    print(f"Analyzing TODOs in {args.directory}...", file=sys.stderr)
    results = find_and_analyze(args.directory, args.min_age)
    
    html = generate_html(results, args.directory)
    
    output_path = Path(args.output)
    output_path.write_text(html, encoding='utf-8')
    
    print(f"HTML report written to {output_path}", file=sys.stderr)
    print(f"Found {len(results)} TODOs", file=sys.stderr)
    
    # Try to open in browser
    try:
        import webbrowser
        webbrowser.open(f'file://{output_path.resolve()}')
    except Exception:
        pass


if __name__ == '__main__':
    main()
